(initial-fact)
(employee (lastname Al-Bishi) (dept sales) (xp 4))
(employee (lastname Dabbagh) (dept sales) (xp 4))
(employee (lastname Al-Habsi) (dept sales) (xp 5))
(employee (lastname Al-Hallaq) (dept sales) (xp 5))
