(initial-fact)
(employee (lastname Al-Bishi) (dept sales) (xp 4))
(employee (lastname Akram) (dept cleaning) (xp 4))
(employee (lastname Dabbagh) (dept sales) (xp 4))
(employee (lastname Damji) (dept sales) (xp 4))
